### ISSUE TITLE
Screenshots in Readme

### ISSUE THREAD

**Issue by JonasLoos** [doc97/Neon-Domination#1]
I recommend adding some screenshots to the readme.md, so one gets a better impression before downloading.

Just an idea, so just remove this issue if you think it's not good :sweat_smile:

**Comment by doc97** [comment]
Hi

thanks for showing interest in our project! For me this project was more of a practice project so I did not think it would be necessary but you're right. Screenshots are definitely important when trying to attract users, I'll ask my friend to add them. 😎

**Comment by warriormaster12** [comment]
@JonasLoos thank you for your suggestion, I have now added screenshots and a link to a showcase ;)
